import { File, Paths } from 'expo-file-system';
import * as DocumentPicker from 'expo-document-picker';
import * as Sharing from 'expo-sharing';
import * as SQLite from 'expo-sqlite';
import type { SQLiteDatabase } from 'expo-sqlite';
import { createMobileBackupManifest, type MobileBackupAttachmentRow } from '@proofvault/domain';

const requiredTables=['inventory_items','item_attachments','valuation_records','comparable_listings','incidents','incident_items','app_settings'];

export async function shareDatabaseBackup(db:SQLiteDatabase){if(!await Sharing.isAvailableAsync())throw new Error('Sharing is not available on this device.');const bytes=await db.serializeAsync();const file=new File(Paths.cache,`ProofVault_database_${new Date().toISOString().slice(0,10)}_${Date.now()}.sqlite`);file.create();file.write(bytes);await Sharing.shareAsync(file.uri,{mimeType:'application/vnd.sqlite3',dialogTitle:'Save ProofVault database backup',UTI:'public.database'});}

export async function shareAttachmentManifest(db:SQLiteDatabase){if(!await Sharing.isAvailableAsync())throw new Error('Sharing is not available on this device.');const inventoryRows=await db.getAllAsync<{id:string;attachment_type:string;local_uri:string;mime_type:string|null;original_name:string|null;item_id:string;item_name:string;created_at:string}>('SELECT item_attachments.id,item_attachments.attachment_type,item_attachments.local_uri,item_attachments.mime_type,item_attachments.original_name,item_attachments.item_id,inventory_items.item_name,item_attachments.created_at FROM item_attachments JOIN inventory_items ON inventory_items.id=item_attachments.item_id ORDER BY item_attachments.created_at');const incidentRows=await db.getAllAsync<{id:string;local_uri:string;mime_type:string|null;original_name:string|null;incident_id:string;title:string;item_id:string;item_name:string;created_at:string}>('SELECT incident_attachments.id,incident_attachments.local_uri,incident_attachments.mime_type,incident_attachments.original_name,incident_attachments.incident_id,incidents.title,incident_attachments.item_id,inventory_items.item_name,incident_attachments.created_at FROM incident_attachments JOIN incidents ON incidents.id=incident_attachments.incident_id JOIN inventory_items ON inventory_items.id=incident_attachments.item_id ORDER BY incident_attachments.created_at');const attachments:MobileBackupAttachmentRow[]=[...inventoryRows.map(row=>({id:row.id,scope:'inventory-item' as const,attachmentType:row.attachment_type,localUri:row.local_uri,mimeType:row.mime_type??undefined,originalName:row.original_name??undefined,inventoryItemId:row.item_id,inventoryItemName:row.item_name,createdAt:row.created_at})),...incidentRows.map(row=>({id:row.id,scope:'incident-item' as const,attachmentType:'incident-photo',localUri:row.local_uri,mimeType:row.mime_type??undefined,originalName:row.original_name??undefined,inventoryItemId:row.item_id,inventoryItemName:row.item_name,incidentId:row.incident_id,incidentTitle:row.title,createdAt:row.created_at}))];const manifest=createMobileBackupManifest(attachments);const file=new File(Paths.cache,`ProofVault_attachment_manifest_${new Date().toISOString().slice(0,10)}_${Date.now()}.json`);file.create();file.write(JSON.stringify(manifest,null,2));await Sharing.shareAsync(file.uri,{mimeType:'application/json',dialogTitle:'Save ProofVault attachment manifest',UTI:'public.json'});}

export async function pickDatabaseBackup(){const result=await DocumentPicker.getDocumentAsync({type:['application/vnd.sqlite3','application/x-sqlite3','application/octet-stream'],copyToCacheDirectory:true,multiple:false});if(result.canceled)return undefined;return await new File(result.assets[0].uri).bytes();}

export async function restoreDatabaseBackup(db:SQLiteDatabase,bytes:Uint8Array){const header=new TextDecoder().decode(bytes.slice(0,16));if(!header.startsWith('SQLite format 3'))throw new Error('This file is not a valid SQLite database.');const imported=await SQLite.deserializeDatabaseAsync(bytes);try{const integrity=await imported.getFirstAsync<{integrity_check:string}>('PRAGMA integrity_check');if(integrity?.integrity_check!=='ok')throw new Error('The backup failed its SQLite integrity check.');const tables=await imported.getAllAsync<{name:string}>("SELECT name FROM sqlite_master WHERE type='table'");const names=new Set(tables.map(table=>table.name));if(requiredTables.some(table=>!names.has(table)))throw new Error('This is not a complete ProofVault database backup.');await SQLite.backupDatabaseAsync({sourceDatabase:imported,sourceDatabaseName:'main',destDatabase:db,destDatabaseName:'main'});}finally{await imported.closeAsync();}}
